### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Review by tkphd — APPROVED** [review]
Thanks!

**Comment by psteinb** [comment]
In the admittedly rather unlikely case github changes it's URL system, this will again be broken. Shouldn't it rather be
```
[zip file with a small application]({{
page.root }}/downloads/filesystem.zip)
```

**Comment by bkmgit** [comment]
Ok. Before we had `[zip file with a small application]({{ page.root }}/code/02_parallel_jobs/fdate.zip)` Will try your suggestion on another broken link.

**Comment by psteinb** [comment]
Excellent idea. I like that.

**Comment by bkmgit** [comment]
@psteinb https://github.com/hpc-carpentry/hpc-parallel-novice/pull/25

**Pull request merged**
