### PR TITLE
Sync upstream lesson_check

### PR DESCRIPTION
**Pull request by tkphd**
[carpentries/lesson-example](https://github.com/carpentries/lesson-example/) updated `lesson_check.py` to accept any `language-*` code block, along with a few minor changes.

### CODE REVIEW

**Comment by bkmgit** [comment]
Thanks.

**Comment by bkmgit** [comment]
Running make lesson-check-all gives:
bin/lesson_check.py:384: FutureWarning: Possible nested set at position 2
  (not re.search(link, l)) and
./_episodes/05-bonus-mpi-for-pi.md: Line(s) too long: 38
./design.md: Line(s) too long: 23, 39

**Comment by bkmgit** [comment]
Based on the issue https://github.com/jekyll/jekyll/issues/5267 it would be helpful to add vendor to _config.yml to enable local builds.

**Comment by bkmgit** [comment]
When previewing locally, the header title appears twice
DoubleHeader

**Comment by tkphd** [comment]
@bkmgit [wrote](#issuecomment-824565853):

> Running make lesson-check-all gives:
> ```
> bin/lesson_check.py:384: FutureWarning: Possible nested set at position 2
> (not re.search(link, l)) and
> ./_episodes/05-bonus-mpi-for-pi.md: Line(s) too long: 38
> ./design.md: Line(s) too long: 23, 39
> ```

An interesting warning about some of our custom code. Since this is not an *error*, we could let it slide; but it does refer to a customization of our own,

```python
link = '^[[].+[]]:' # regex for [link-abbrv]: address
over = [i for (i, l, n) in self.lines if (n > MAX_LINE_LEN) and
                                      (not l.startswith('!')) and
                                      (not re.search(code, l)) and
                                      (not re.search(link, l)) and
                                      (not l.startswith('http'))]
```

Is anybody better-versed with regular expressions able to comment?

**Comment by tkphd** [comment]
@bkmgit [wrote](#issuecomment-824570367):

> Based on the issue [jekyll/jekyll#5267](https://github.com/jekyll/jekyll/issues/5267) it would be helpful to add "vendor" to `_config.yml` to enable local builds.

[`.vendor` is already excluded.](https://github.com/hpc-carpentry/hpc-parallel-novice/blob/d9fac058d4917ba3f10cc9daba43515eb8fcb58b/_config.yml#L89)

The linked issue refers to running `jekyll serve`, which circumvents the Bundler framework (and which created the `.vendor` folder to begin with). Was an error thrown by `make site` or `make serve`? These call Jekyll through Bundler, ensuring the local configuration is recognized.

**Comment by tkphd** [comment]
@bkmgit [wrote](#commitcomment-49837890):

> ```markdown
> [coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html
> [coc-reporting]: https://docs.carpentries.org/topic_folders/policies/incident-reporting.html
> ```
> are in `links.md` - why do they need to be included again in `CODE_OF_CONDUCT.md`?

I agree that this is an unfortunate repetition. Without making these definitions, `make lesson-check` throws an error:
```bash
./CODE_OF_CONDUCT.md: Internally-defined links may be missing definitions: "Carpentry Code of Conduct"=>"coc", "reporting guidelines"=>"coc-reporting"
make: *** [Makefile:134: lesson-check] Error 1
```

**Comment by tkphd** [comment]
@bkmgit [wrote](#commitcomment-49838692):

> May consider using [regex](https://pypi.org/project/regex/) instead of [re](https://docs.python.org/3/library/re.html) due to better unicode support.

Excellent suggestion for the [upstream maintainers](https://github.com/carpentries/lesson-example/issues).

**Comment by tkphd** [comment]
@bkmgit [wrote](#issuecomment-824686247):

> When previewing locally, the header title appears twice

Yeah, it does that, and I have no idea why. The double-header *does not* appear on the deployed site: this is restricted to local builds only.

Fixing this local-rendering bug is out-of-scope for this PR.

**Comment by bkmgit** [comment]
> @bkmgit [wrote](#issuecomment-824570367):
> 
> > Based on the issue [jekyll/jekyll#5267](https://github.com/jekyll/jekyll/issues/5267) it would be helpful to add "vendor" to `_config.yml` to enable local builds.
> 
> [`.vendor` is already excluded.](https://github.com/hpc-carpentry/hpc-parallel-novice/blob/d9fac058d4917ba3f10cc9daba43515eb8fcb58b/_config.yml#L89)
> 
> The linked issue refers to running `jekyll serve`, which circumvents the Bundler framework (and which created the `.vendor` folder to begin with). Was an error thrown by `make site` or `make serve`? These call Jekyll through Bundler, ensuring the local configuration is recognized.

Needed to add vendor explicitly for it to build, error is thrown by both `make serve` and `make build`, vendor is not always a hidden directory.

**Comment by bkmgit** [comment]
Not sure if this should be an upstream change though.

**Comment by tkphd** [comment]
Thanks @bkmgit, this is a good cross-platform catch!

**Review by psteinb — APPROVED** [review]
Super important. Thanks!

**Pull request merged**
